'use client';

import * as React from 'react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from 'recharts';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { cn } from '@/lib/utils';

interface VendorPerformanceChartProps {
  className?: string;
  data?: Array<{ name: string; revenue: number; orders: number; rating?: number }>;
  isLoading?: boolean;
}

const COLORS = ['#3b82f6', '#8b5cf6', '#ec4899', '#f59e0b', '#10b981', '#ef4444', '#6366f1', '#14b8a6'];

export function VendorPerformanceChart({
  className,
  data = [],
  isLoading = false,
}: VendorPerformanceChartProps) {
  const chartData = data.length > 0 ? data : [{ name: 'No Data', revenue: 0 }];

  return (
    <Card className={cn('col-span-2', className)}>
      <CardHeader>
        <CardTitle>Top Performing Vendors</CardTitle>
        <p className="text-sm text-muted-foreground">
          {isLoading ? 'Loading...' : 'Revenue generated by vendors'}
        </p>
      </CardHeader>
      <CardContent>
        <div className="h-[300px]">
          {isLoading ? (
            <div className="flex items-center justify-center h-full">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
            </div>
          ) : (
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} layout="vertical">
                <CartesianGrid
                  strokeDasharray="3 3"
                  className="stroke-muted"
                  horizontal={false}
                />
                <XAxis
                  type="number"
                  className="text-xs text-muted-foreground"
                  tickFormatter={(value) => `Ksh ${value}`}
                />
                <YAxis
                  dataKey="name"
                  type="category"
                  className="text-xs text-muted-foreground"
                  width={100}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: 'hsl(var(--background))',
                    border: '1px solid hsl(var(--border))',
                    borderRadius: '8px',
                    boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                  }}
                  formatter={(value: number) => [`Ksh ${value}`, 'Revenue']}
                />
                <Bar dataKey="revenue" radius={[0, 4, 4, 0]}>
                  {chartData.map((entry, index) => (
                    <Cell
                      key={`cell-${index}`}
                      fill={COLORS[index % COLORS.length]}
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          )}
        </div>
      </CardContent>
    </Card>
  );
}